# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0002_remove_pushnotification_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='devices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='push_notifications.Device'),
        ),
    ]
