# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-27 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0003_pushnotification_devices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotification',
            old_name='devices',
            new_name='device',
        ),
    ]
